package com.shpetny.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.annotation.Generated;
import java.time.LocalDateTime;

/**
 * @author Shpetny Eugene
 * @version 1.0
 */
@Document(collection = "events")
public class Event {
    @Id
    // TODO Add autogenerated
    private long id;
    private String name;
    private int groupID;
    private LocalDateTime dateTime;
    private Coordinate coordinate;


    public Event(String name, int groupID, LocalDateTime dateTime, Coordinate coordinate) {
        this.name = name;
        this.groupID = groupID;
        this.dateTime = dateTime;
        this.coordinate = coordinate;
    }
}
